class SupportedClass {
  static const List<String> labels = [
    'người',
    'xe đạp',
    'xe hơi',
    'xe máy',
    'xe buýt',
    'tàu hỏa',
    'xe tải',
    'thuyền',
    'ghế dài',
    'chim',
    'mèo',
    'chó',
    'ba lô',
    'dù',
    'túi xách',
    'cà vạt',
    'vali',
    'diều',
    'chai',
    'ghế',
    'ghế sofa',
    'chậu cây',
    'giường',
    'bàn',
    'bồn cầu',
    'tivi',
    'laptop',
    'chuột máy tính',
    'điều khiển',
    'bàn phím',
    'điện thoại',
    'lò vi sóng',
    'lò nướng',
    'máy nướng bánh',
    'bồn rửa',
    'tủ lạnh',
    'sách',
    'đồng hồ',
    'lọ hoa',
    'kéo',
    'bàn chải',
    'chén',
    'muỗng',
    'nĩa',
    'ly',
    'dao',
    'cầu thang',
    'hồ bơi',
    'quạt máy',
    'vòi sen',
    'tay nắm cửa',
    'kệ sách',
    'bút',
    'rắn',
    'tủ quần áo',
    'bàn cà phê',
    'ví',
  ];
}
